version: 1.0.{build}
image: Visual Studio 2019
before_build:
  - ps: dotnet restore Duplicati.sln -p:nowarn=NU1701
build_script:
  - ps: dotnet build Duplicati.sln --no-restore
before_test:
  - ps: $env:UNITTEST_BASEFOLDER = "$Env:APPVEYOR_BUILD_FOLDER" + "\testdata"
test_script:
  - ps: |
      $testProject = ".\Duplicati\UnitTest\Duplicati.UnitTest.csproj"
      dotnet add $testProject package Appveyor.TestLogger --version 2.0.0

      $testCategories = @(
        "Border",
        "BulkData"
        "BulkNormal",
        "BulkNoSize",
        "Compression"
        "Disruption",
        "Filter",
        "ImportExport",
        "IO",
        "Purge",
        "Serialization",
        "SVNData",
        "SVNDataLong",
        "Targeted",
        "Utility",
        "UriUtility",
        "WebApi"
      )
      dotnet test $testProject --no-restore --filter "Category=$($testCategories -join "|")" --test-adapter-path:. --logger:Appveyor
